// API types

export const ENDPOINT = 'ENDPOINT'

// Sidebar types
export const OPEN_SIDEBAR = 'OPEN_SIDEBAR'
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR'

// Authenticaction types
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT = 'LOGOUT'

// Boxstate types

export const SET_SEARCH_TYPE = 'SET_SEARCH_TYPE'
export const SET_DEVICE_NUMBER = 'SET_DEVICE_NUMBER'
export const PREV_INFO_REQUEST = 'PREV_INFO_REQUEST'
export const PREV_INFO_FAILURE = 'PREV_INFO_FAILURE'
export const PREV_INFO_SUCCESS = 'PREV_INFO_SUCCESS'
export const BOX_INFO_REQUEST = 'BOX_INFO_REQUEST'
export const BOX_INFO_FAILURE = 'BOX_INFO_FAILURE'
export const BOX_INFO_SUCCESS = 'BOX_INFO_SUCCESS'

// Transformers types

export const SET_TRANSFORMER_REQUEST_STATUS = 'SET_TRANSFORMER_REQUEST_STATUS'
export const GET_ALL_TRANSFORMERS = 'GET_ALL_TRANSFORMERS'
export const GET_TRANSFORMER_DATA = 'GET_TRANSFORMER_DATA'

// Transform Activites Reducer

// Stakeout
export const ADD_TRANSFORMER_STAKEOUT = 'ADD_TRANSFORMER_STAKEOUT'
export const DEL_TRANSFORMER_STAKEOUT = 'DEL_TRANSFORMER_STAKEOUT'
export const LOAD_TRANSFORMER_STAKEOUT = 'LOAD_TRANSFORMER_STAKEOUT'
export const GET_TRANSFORMER_STAKEOUTS = 'GET_TRANSFORMER_STAKEOUTS'
export const ADD_STAKEOUT_NODE = 'ADD_STAKEOUT_NODE'
export const DEL_STAKEOUT_NODE = 'DEL_STAKEOUT_NODE'
export const ADD_STAKEOUT_USER = 'ADD_STAKEOUT_USER'
export const DEL_STAKEOUT_USER = 'DEL_STAKEOUT_USER'
export const ADD_STAKEOUT_CHARGUE = 'ADD_STAKEOUT_CHARGUE'
export const DEL_STAKEOUT_CHARGUE = 'DEL_STAKEOUT_CHARGUE'