// API types

export const ENDPOINT = 'ENDPOINT'
export const SET_API_IP = 'SET_API_IP'

// Sidebar types
export const OPEN_SIDEBAR = 'OPEN_SIDEBAR'
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR'

// Authenticaction types
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT = 'LOGOUT'

// Boxstate types

export const SET_SEARCH_TYPE = 'SET_SEARCH_TYPE'
export const SET_DEVICE_NUMBER = 'SET_DEVICE_NUMBER'
export const PREV_INFO_REQUEST = 'PREV_INFO_REQUEST'
export const PREV_INFO_FAILURE = 'PREV_INFO_FAILURE'
export const PREV_INFO_SUCCESS = 'PREV_INFO_SUCCESS'
export const BOX_INFO_REQUEST = 'BOX_INFO_REQUEST'
export const BOX_INFO_FAILURE = 'BOX_INFO_FAILURE'
export const BOX_INFO_SUCCESS = 'BOX_INFO_SUCCESS'

// Transformers types

export const SET_TRANSFORMER_REQUEST_STATUS = 'SET_TRANSFORMER_REQUEST_STATUS'
export const GET_ALL_TRANSFORMERS = 'GET_ALL_TRANSFORMERS'
export const GET_TRANSFORMER_DATA = 'GET_TRANSFORMER_DATA'

// Balanace Types

export const SET_TRANSFORMER_USER_STATUS = 'SET_TRANSFORMER_USER_STATUS'

// Transform Activites Reducer
export const REGISTER_LOG_EVENT = 'REGISTER_LOG_EVENT'
export const UPDATE_TRANSFORMER_DOWNLOAD_STATUS = 'UPDATE_TRANSFORMER_DOWNLOAD_STATUS'
export const DOWNLOAD_TRANSFORMER_DATA_TO_LOCAL = 'DOWNLOAD_TRANSFORMER_DATA_TO_LOCAL'
export const ADD_LOCAL_TRANSFORMER = 'REGISTER_LOCAL_TRANSFORMER'
export const DELETE_LOCAL_TRANSFORMER = 'DELETE_LOCAL_TRANSFORMER'
export const ADD_LOCAL_TRANSFORMER_USERS = 'DELETE_LOCAL_TRANSFORMER_USERS'
export const DELETE_LOCAL_TRANSFORMER_USERS = 'DELETE_LOCAL_TRANSFORMER_USERS'
export const SET_LOCAL_TRANSFORMER_DATA_STATUS = 'SET_LOCAL_TRANSFORMER_STATUS'
export const SET_ASIGNED_TRANSFORMER_ACTIVITIES = 'SET_ASIGNED_TRANSFORMER_ACTIVITIES'
export const SET_ACTUAL_ACTIVITY = 'SET_ACTUAL_ACTIVITY'
export const CLEAR_ACTUAL_ACTIVITY = 'CLEAR_ACTUAL_ACTIVITY'
export const SET_ACTUAL_NODES = 'SET_ACTUAL_NODES'
export const CLEAR_ACTUAL_NODES = 'CLEAR_ACTUAL_NODES'
export const SET_ACTUAL_TRANSFORMER_USERS = 'SET_ACTUAL_TRANSFORMER_USERS'
export const CLEAR_ACTUAL_TRANSFORMER_USERS = 'CLEAR_ACTUAL_TRANSFORMER_USERS'
export const SET_ACTUAL_STAKEOUT_USER = 'SET_ACTUAL_STAKEOUT_USER'
export const CLEAR_ACTUAL_STAKEOUT_USER = 'CLEAR_ACTUAL_STAKEOUT_USER'
export const SET_ACTUAL_NODE_USERS = 'SET_ACTUAL_NODE_USERS'
export const CLEAR_ACTUAL_NODE_USERS = 'CLEAR_ACTUAL_NODE_USERS'
export const SET_ACTUAL_USER_LECTURES = 'SET_ACTUAL_USER_LECTURE'
export const CLEAR_ACTUAL_USER_LECTURES = 'CLEAR_ACTUAL_USER_LECTURE'
export const SET_ACTUAL_NODE_OCS = 'SET_ACTUAL_NODE_OCS'
export const CLEAR_ACTUAL_NODE_OCS = 'CLEAR_ACTUAL_NODE_OCS'
export const SET_ACTUAL_ACTIVITY_BADLINKS = 'SET_ACTUAL_ACTIVITY_BADLINKS'
export const CLEAR_ACTUAL_ACTIVITY_BADLINKS = 'CLEAR_ACTUAL_ACTIVITY_BADLINKS'
export const SET_ACTUAL_STAKEOUT_PROGRESS = 'SET_ACTUAL_STAKEOUT_PROGRESS'
export const CLEAR_ACTUAL_STAKEOUT_PROGRESS = 'CLEAR_ACTUAL_STAKEOUT_PROGRESS'